# Generated by Django 4.2.23 on 2025-09-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaccaraConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='설정 ID')),
                ('logic1_enabled', models.BooleanField(default=True, verbose_name='로직1 활성화')),
                ('logic2_enabled', models.BooleanField(default=True, verbose_name='로직2 활성화')),
                ('logic3_enabled', models.BooleanField(default=True, verbose_name='로직3 활성화')),
                ('logic4_enabled', models.BooleanField(default=True, verbose_name='로직4 활성화')),
                ('ai_logic_enabled', models.BooleanField(default=False, verbose_name='AI 로직 활성화 (추후)')),
                ('logic2_patterns', models.JSONField(blank=True, default=list, null=True, verbose_name='로직2 패턴 시퀀스 (배열의 배열)')),
                ('logic3_patterns', models.JSONField(blank=True, default=dict, null=True, verbose_name='로직3 패턴 정의 (개수 및 시퀀스)')),
                ('profit_rate', models.TextField(blank=True, verbose_name='수익률 설정')),
                ('another_setting', models.CharField(blank=True, max_length=255, verbose_name='기타 설정')),
            ],
            options={
                'verbose_name': '바카라 설정',
                'verbose_name_plural': '바카라 설정',
                'db_table': 'baccara_config',
            },
        ),
        migrations.CreateModel(
            name='ClsLog',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('gubun', models.CharField(blank=True, max_length=50, verbose_name='로그 구분')),
                ('log', models.TextField(blank=True, verbose_name='로그 내용')),
                ('log_datetime', models.DateTimeField(auto_now_add=True, verbose_name='로그 시간')),
            ],
            options={
                'verbose_name': '클래스 로그',
                'verbose_name_plural': '클래스 로그',
                'db_table': 'clslog',
                'ordering': ['-log_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ThreeTicket',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('memberid', models.CharField(default='0', max_length=50, unique=True, verbose_name='회원 ID')),
                ('_pattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='_Pattern')),
                ('tpattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='TPattern')),
                ('upattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='UPattern')),
                ('npattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='NPattern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threeticket_record', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '3매 티켓',
                'verbose_name_plural': '3매 티켓',
                'db_table': '3ticket',
            },
        ),
        migrations.CreateModel(
            name='SixTicket',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('memberid', models.CharField(default='0', max_length=50, unique=True, verbose_name='회원 ID')),
                ('_pattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='_Pattern')),
                ('tpattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='TPattern')),
                ('upattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='UPattern')),
                ('npattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='NPattern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sixticket_record', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '6매 티켓',
                'verbose_name_plural': '6매 티켓',
                'db_table': '6ticket',
            },
        ),
        migrations.CreateModel(
            name='FourTicket',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('memberid', models.CharField(default='0', max_length=50, unique=True, verbose_name='회원 ID')),
                ('_pattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='_Pattern')),
                ('tpattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='TPattern')),
                ('upattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='UPattern')),
                ('npattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='NPattern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fourticket_record', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '4매 티켓',
                'verbose_name_plural': '4매 티켓',
                'db_table': '4ticket',
            },
        ),
        migrations.CreateModel(
            name='FiveTicket',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('memberid', models.CharField(default='0', max_length=50, unique=True, verbose_name='회원 ID')),
                ('_pattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='_Pattern')),
                ('tpattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='TPattern')),
                ('upattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='UPattern')),
                ('npattern', models.JSONField(blank=True, default=dict, null=True, verbose_name='NPattern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiveticket_record', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '5매 티켓',
                'verbose_name_plural': '5매 티켓',
                'db_table': '5ticket',
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('event', '이벤트'), ('warning', '경고'), ('info', '정보'), ('system', '시스템')], default='notice', max_length=20, verbose_name='카테고리')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '전체 공지 메시지',
                'verbose_name_plural': '전체 공지 메시지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaccaraDB',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('memberid', models.CharField(default='0', max_length=50, unique=True, verbose_name='회원 ID')),
                ('dayinfo', models.CharField(blank=True, default='0', max_length=10, verbose_name='날짜 정보')),
                ('bcdata', models.TextField(blank=True, verbose_name='바카라 데이터 (조보 문자열)')),
                ('basetable', models.TextField(blank=True, verbose_name='베이스 테이블')),
                ('Pattern_3', models.JSONField(blank=True, default=list, null=True, verbose_name='3Pattern')),
                ('Pattern_4', models.JSONField(blank=True, default=list, null=True, verbose_name='4Pattern')),
                ('Pattern_5', models.JSONField(blank=True, default=list, null=True, verbose_name='5Pattern')),
                ('Pattern_6', models.JSONField(blank=True, default=list, null=True, verbose_name='6Pattern')),
                ('ptn', models.TextField(blank=True, verbose_name='패턴 (ptn)')),
                ('ptnhistory', models.TextField(blank=True, verbose_name='패턴 히스토리')),
                ('baseresult', models.TextField(blank=True, verbose_name='기본 결과')),
                ('coininfo', models.TextField(blank=True, verbose_name='코인 정보')),
                ('chartResult', models.JSONField(blank=True, default=dict, null=True, verbose_name='차트 결과')),
                ('pattern_stats', models.JSONField(blank=True, default=dict, null=True, verbose_name='패턴 통계')),
                ('logic_state', models.JSONField(blank=True, default=dict, null=True, verbose_name='로직 상태')),
                ('logic3_patterns', models.JSONField(blank=True, default=dict, null=True, verbose_name='로직3 패턴 (구버전)')),
                ('analytics_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='분석 데이터')),
                ('virtual_stats', models.JSONField(blank=True, default=dict, null=True, verbose_name='가상 통계')),
                ('game_history', models.JSONField(blank=True, default=list, null=True, verbose_name='게임 히스토리')),
                ('logic2_state', models.JSONField(blank=True, default=dict, null=True, verbose_name='로직2 상태 (구버전)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bacaradb_profile', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '바카라 게임 데이터',
                'verbose_name_plural': '바카라 게임 데이터',
                'db_table': 'bacaradb',
            },
        ),
    ]
