# Generated by Django 4.2.10 on 2025-09-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaccaraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic1_enabled', models.BooleanField(default=True, verbose_name='로직1 활성화')),
                ('logic2_enabled', models.BooleanField(default=True, verbose_name='로직2 활성화')),
                ('logic3_enabled', models.BooleanField(default=True, verbose_name='로직3 활성화')),
                ('logic4_enabled', models.BooleanField(default=True, verbose_name='로직4 활성화')),
                ('ai_logic_enabled', models.BooleanField(default=False, verbose_name='AI 로직 활성화 (추후)')),
                ('logic2_patterns', models.JSONField(blank=True, default=list, null=True, verbose_name='로직2 패턴 시퀀스 (배열의 배열)')),
                ('logic3_patterns', models.JSONField(blank=True, default=dict, null=True, verbose_name='로직3 패턴 정의 (개수 및 시퀀스)')),
                ('profit_rate', models.TextField(blank=True, verbose_name='수익률 설정')),
                ('another_setting', models.CharField(blank=True, max_length=255, verbose_name='기타 설정')),
            ],
            options={
                'verbose_name': '바카라 설정',
                'verbose_name_plural': '바카라 설정',
            },
        ),
        migrations.CreateModel(
            name='BaccaraDB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dayinfo', models.CharField(default='0', max_length=10)),
                ('bcdata', models.CharField(max_length=1000)),
                ('basetable', models.CharField(max_length=1000)),
                ('pattern_3', models.JSONField(default=list)),
                ('pattern_4', models.JSONField(default=list)),
                ('virtual_stats', models.JSONField(blank=True, default=dict, null=True)),
                ('game_history', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': '바카라 게임 데이터',
                'verbose_name_plural': '바카라 게임 데이터',
                'db_table': 'bacaradb',
            },
        ),
        migrations.CreateModel(
            name='ClsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('event', '이벤트'), ('warning', '경고'), ('info', '정보'), ('system', '시스템')], default='notice', max_length=20, verbose_name='카테고리')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '전체 공지 메시지',
                'verbose_name_plural': '전체 공지 메시지',
                'ordering': ['-created_at'],
            },
        ),
    ]
