# Generated by Django 4.2.23 on 2025-09-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccaradb',
            name='selected_logic',
            field=models.CharField(default='logic1', max_length=10, verbose_name='선택된 로직'),
        ),
    ]
